export const CREATE_ANNOUNCEMENT_REQUEST="CREATE_ANNOUNCEMENT_REQUEST";
export const CREATE_ANNOUNCEMENT_SUCCESS="CREATE_ANNOUNCEMENT_SUCCESS";
export const CREATE_ANNOUNCEMENT_RESET="CREATE_ANNOUNCEMENT_RESET";
export const CREATE_ANNOUNCEMENT_FAIL="CREATE_ANNOUNCEMENT_FAIL";

export const GET_ANNOUNCEMENTS_REQUEST = "GET_ANNOUNCEMENTS_REQUEST";
export const GET_ANNOUNCEMENTS_SUCCESS = "GET_ANNOUNCEMENTS_SUCCESS";
export const GET_ANNOUNCEMENTS_FAIL = "GET_ANNOUNCEMENTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";