export const APPLICATION_STATUS_SUCCESS = "APPLICATION_STATUS_SUCCESS";
export const APPLICATION_STATUS_REQUEST = "APPLICATION_STATUS_REQUEST";
export const APPLICATION_STATUS_FAIL = "APPLICATION_STATUS_FAIL";

export const APPLY_SUCCESS = "APPLY_SUCCESS";
export const APPLY_REQUEST = "APPLY_REQUEST";
export const APPLY_FAIL = "APPLY_FAIL";
export const APPLY_RESET = "APPLY_RESET";

export const WITHDRAW_SUCCESS = "WITHDRAW_SUCCESS";
export const WITHDRAW_REQUEST = "WITHDRAW_REQUEST";
export const WITHDRAW_FAIL = "WITHDRAW_FAIL";
export const WITHDRAW_RESET = "WITHDRAW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";