export const CREATE_COMPANY_REQUEST="CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS="CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAIL="CREATE_COMPANY_FAIL";

export const UPCOMING_COMPANIES_REQUEST = "UPCOMING_COMPANIES_REQUEST";
export const UPCOMING_COMPANIES_SUCCESS = "UPCOMING_COMPANIES_SUCCESS";
export const UPCOMING_COMPANIES_FAIL = "UPCOMING_COMPANIES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
