export const CREATE_COMPANY_REQUEST="CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS="CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAIL="CREATE_COMPANY_FAIL";
export const CREATE_COMPANY_RESET="CREATE_COMPANY_RESET";

export const EDIT_COMPANY_REQUEST="EDIT_COMPANY_REQUEST";
export const EDIT_COMPANY_SUCCESS="EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAIL="EDIT_COMPANY_FAIL";
export const EDIT_COMPANY_RESET="EDIT_COMPANY_RESET";

export const DELETE_COMPANY_REQUEST="DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS="DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL="DELETE_COMPANY_FAIL";
export const DELETE_COMPANY_RESET="DELETE_COMPANY_RESET";

export const UPCOMING_COMPANIES_REQUEST = "UPCOMING_COMPANIES_REQUEST";
export const UPCOMING_COMPANIES_SUCCESS = "UPCOMING_COMPANIES_SUCCESS";
export const UPCOMING_COMPANIES_FAIL = "UPCOMING_COMPANIES_FAIL";

export const REGISTERED_STUDENTS_REQUEST = "REGISTERED_STUDENTS_REQUEST";
export const REGISTERED_STUDENTS_SUCCESS = "REGISTERED_STUDENTS_SUCCESS";
export const REGISTERED_STUDENTS_FAIL = "REGISTERED_STUDENTS_FAIL";

export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
