export const GET_COORDINATORS_REQUEST = "GET_COORDINATORS_REQUEST";
export const GET_COORDINATORS_SUCCESS = "GET_COORDINATORS_SUCCESS";
export const GET_COORDINATORS_FAIL = "GET_COORDINATORS_FAIL";

export const CREATE_COORDINATOR_REQUEST="CREATE_COORDINATOR_REQUEST";
export const CREATE_COORDINATOR_SUCCESS="CREATE_COORDINATOR_SUCCESS";
export const CREATE_COORDINATOR_FAIL="CREATE_COORDINATOR_FAIL";
export const CREATE_COORDINATOR_RESET="CREATE_COORDINATOR_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";