export const CREATE_INTERVIEW_REQUEST="CREATE_INTERVIEW_REQUEST";
export const CREATE_INTERVIEW_SUCCESS="CREATE_INTERVIEW_SUCCESS";
export const CREATE_INTERVIEW_FAIL="CREATE_INTERVIEW_FAIL";
export const CREATE_INTERVIEW_RESET="CREATE_INTERVIEW_RESET";

export const EDIT_INTERVIEW_REQUEST="EDIT_INTERVIEW_REQUEST";
export const EDIT_INTERVIEW_SUCCESS="EDIT_INTERVIEW_SUCCESS";
export const EDIT_INTERVIEW_FAIL="EDIT_INTERVIEW_FAIL";
export const EDIT_INTERVIEW_RESET="EDIT_INTERVIEW_RESET";

export const GET_INTERVIEWS_REQUEST = "GET_INTERVIEWS_REQUEST";
export const GET_INTERVIEWS_SUCCESS = "GET_INTERVIEWS_SUCCESS";
export const GET_INTERVIEWS_FAIL = "GET_INTERVIEWS_FAIL";

export const INTERVIEW_DETAILS_SUCCESS = "INTERVIEW_DETAILS_SUCCESS";
export const INTERVIEW_DETAILS_REQUEST = "INTERVIEW_DETAILS_REQUEST";
export const INTERVIEW_DETAILS_FAIL = "INTERVIEW_DETAILS_FAIL";

export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";
export const UPDATE_STATUS_RESET = "UPDATE_STATUS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";