export const CREATE_NOTIFICATION_REQUEST="CREATE_NOTIFICATION_REQUEST";
export const CREATE_NOTIFICATION_SUCCESS="CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_RESET="CREATE_NOTIFICATION_RESET";
export const CREATE_NOTIFICATION_FAIL="CREATE_NOTIFICATION_FAIL";

export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";