export const CREATE_PLACEMENT_REQUEST="CREATE_PLACEMENT_REQUEST";
export const CREATE_PLACEMENT_SUCCESS="CREATE_PLACEMENT_SUCCESS";
export const CREATE_PLACEMENT_FAIL="CREATE_PLACEMENT_FAIL";
export const CREATE_PLACEMENT_RESET="CREATE_PLACEMENT_RESET";

export const EDIT_PLACEMENT_REQUEST="EDIT_PLACEMENT_REQUEST";
export const EDIT_PLACEMENT_SUCCESS="EDIT_PLACEMENT_SUCCESS";
export const EDIT_PLACEMENT_FAIL="EDIT_PLACEMENT_FAIL";
export const EDIT_PLACEMENT_RESET="EDIT_PLACEMENT_RESET";

export const GET_PLACEMENTS_REQUEST = "GET_PLACEMENTS_REQUEST";
export const GET_PLACEMENTS_SUCCESS = "GET_PLACEMENTS_SUCCESS";
export const GET_PLACEMENTS_FAIL = "GET_PLACEMENTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";