export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_RESET = "GET_STUDENT_RESET";
export const GET_STUDENT_FAIL = "GET_STUDENT_FAIL";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_RESET = "UPDATE_STUDENT_RESET";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";